name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code with version 2
        uses: actions/checkout@v2
      - name: Check out repository code with version 1
        uses: actions/checkout@v1
      - name: Check out repository code with non existent version
        uses: snyk/actions/python@master
        env:
          SNYK_AUTH: ${{ secrets.SNYK_TOKEN }}