name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    # env:
      # SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Check out repository code with version 2
        uses: actions/checkout@v2
      - name: Check out repository code with version 1
        uses: actions/checkout@v1
      - name: Test out snyk
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}